version: 2

sources:
  - name: census
    database: realty_insights  
    schema: raw_census
    tables:
      - name: census_acs5_base_zcta
        description: Raw data from the Census ACS5 Base ZCTA table.
      - name: census_acs5_base_county
      - name: census_acs5_base_us
      - name: census_acs5_data_profile_zcta
      - name: census_acs5_data_profile_county
      - name: census_acs5_data_profile_us
      - name: census_acs5_subject_zcta
      - name: census_acs5_subject_county
      - name: census_acs5_subject_us
      - name: stg_value_annotations

  - name: realtor
    database: realty_insights
    schema: raw_realtor
    tables:
      - name: realtor_zip
      - name: realtor_county
      - name: realtor_metro
      - name: realtor_state
      - name: realtor_us
